// Organicity — the interface's remaining texts, by their English wording: panel headings,
// buttons, labels and hints that are built in code rather than looked up by key. The live
// translation layer (i18n.js watchDom) swaps any text node or title that matches one exactly.
// Each entry: English → [Magyar, Deutsch, Français, Español, العربية].
export const PHRASE_LANGS = ['hu', 'de', 'fr', 'es', 'ar'];
export const PHRASES = {
  // panel headings
  'Weather': ['Időjárás', 'Wetter', 'Météo', 'Clima', 'الطقس'],
  'Utilities': ['Közművek', 'Versorgung', 'Services publics', 'Suministros', 'المرافق'],
  'Transit': ['Közlekedés', 'Nahverkehr', 'Transports', 'Transporte', 'النقل العام'],
  'Trade': ['Kereskedelem', 'Handel', 'Commerce', 'Comercio', 'التجارة'],
  'Tax rates': ['Adókulcsok', 'Steuersätze', "Taux d'imposition", 'Tasas de impuestos', 'معدلات الضرائب'],
  'Tax brackets': ['Adósávok', 'Steuerstufen', "Tranches d'impôt", 'Tramos fiscales', 'شرائح الضرائب'],
  'Standings': ['Rangsor', 'Rangliste', 'Classement', 'Clasificación', 'الترتيب'],
  'Sound': ['Hang', 'Ton', 'Son', 'Sonido', 'الصوت'],
  'Simulation': ['Szimuláció', 'Simulation', 'Simulation', 'Simulación', 'المحاكاة'],
  'Services': ['Szolgáltatások', 'Dienste', 'Services', 'Servicios', 'الخدمات'],
  'Service funding': ['Szolgáltatások finanszírozása', 'Finanzierung der Dienste', 'Financement des services', 'Financiación de servicios', 'تمويل الخدمات'],
  'Service priority': ['Szolgáltatási prioritás', 'Priorität der Dienste', 'Priorité des services', 'Prioridad de servicios', 'أولوية الخدمات'],
  'Sandbox': ['Homokozó', 'Sandkasten', 'Bac à sable', 'Modo libre', 'وضع الحرية'],
  'Population': ['Népesség', 'Bevölkerung', 'Population', 'Población', 'السكان'],
  'Ordinances': ['Rendeletek', 'Verordnungen', 'Arrêtés', 'Ordenanzas', 'المراسيم'],
  'Neighbouring cities': ['Szomszédos városok', 'Nachbarstädte', 'Villes voisines', 'Ciudades vecinas', 'المدن المجاورة'],
  'Monthly budget': ['Havi költségvetés', 'Monatshaushalt', 'Budget mensuel', 'Presupuesto mensual', 'الميزانية الشهرية'],
  'Loans': ['Hitelek', 'Kredite', 'Prêts', 'Préstamos', 'القروض'],
  'Land tax': ['Földadó', 'Grundsteuer', 'Taxe foncière', 'Impuesto territorial', 'ضريبة الأرض'],
  'Industry': ['Ipar', 'Industrie', 'Industrie', 'Industria', 'الصناعة'],
  'History': ['Történet', 'Verlauf', 'Historique', 'Historial', 'السجل'],
  'Health & safety': ['Egészség és biztonság', 'Gesundheit & Sicherheit', 'Santé et sécurité', 'Salud y seguridad', 'الصحة والسلامة'],
  'Graphics': ['Grafika', 'Grafik', 'Graphismes', 'Gráficos', 'الرسومات'],
  'Goods': ['Áruk', 'Waren', 'Marchandises', 'Mercancías', 'البضائع'],
  'Funds': ['Pénz', 'Kasse', 'Fonds', 'Fondos', 'الأموال'],
  'Forecast': ['Előrejelzés', 'Vorhersage', 'Prévisions', 'Pronóstico', 'التوقعات'],
  'Education': ['Oktatás', 'Bildung', 'Éducation', 'Educación', 'التعليم'],
  'Demand': ['Kereslet', 'Nachfrage', 'Demande', 'Demanda', 'الطلب'],
  'Control': ['Irányítás', 'Steuerung', 'Contrôle', 'Control', 'التحكم'],
  'Connection': ['Kapcsolat', 'Verbindung', 'Connexion', 'Conexión', 'الاتصال'],
  'Commuting': ['Ingázás', 'Pendeln', 'Trajets domicile-travail', 'Desplazamientos', 'التنقل اليومي'],
  'City': ['Város', 'Stadt', 'Ville', 'Ciudad', 'المدينة'],
  'City news': ['Városi hírek', 'Stadtnachrichten', 'Nouvelles de la ville', 'Noticias de la ciudad', 'أخبار المدينة'],
  'Chat': ['Csevegés', 'Chat', 'Discussion', 'Chat', 'الدردشة'],
  'Architecture': ['Építészet', 'Architektur', 'Architecture', 'Arquitectura', 'العمارة'],
  'Accessibility': ['Akadálymentesség', 'Barrierefreiheit', 'Accessibilité', 'Accesibilidad', 'إمكانية الوصول'],
  'Era progression': ['Korszakváltás', 'Epochenfortschritt', 'Progression des époques', 'Progreso de épocas', 'تقدم الحقب'],
  'Development rules': ['Beépítési szabályok', 'Bauvorschriften', "Règles d'urbanisme", 'Normas urbanísticas', 'قواعد التطوير'],
  'Vertical development': ['Függőleges beépítés', 'Vertikale Bebauung', 'Développement vertical', 'Desarrollo vertical', 'التطوير العمودي'],
  'Past terms': ['Korábbi ciklusok', 'Frühere Amtszeiten', 'Mandats passés', 'Mandatos anteriores', 'الولايات السابقة'],
  'Presidents of the region': ['A régió elnökei', 'Präsidenten der Region', 'Présidents de la région', 'Presidentes de la región', 'رؤساء الإقليم'],
  'Families living here': ['Itt élő családok', 'Familien, die hier wohnen', 'Familles qui vivent ici', 'Familias que viven aquí', 'العائلات المقيمة هنا'],
  'How life is': ['Milyen itt az élet', 'Wie das Leben ist', 'La vie ici', 'Cómo es la vida', 'كيف هي الحياة'],
  'Next level requirements': ['A következő szint feltételei', 'Bedingungen für die nächste Stufe', 'Conditions du niveau suivant', 'Requisitos del siguiente nivel', 'متطلبات المستوى التالي'],
  'Regional exits': ['Regionális kijáratok', 'Regionale Ausfahrten', 'Sorties régionales', 'Salidas regionales', 'المخارج الإقليمية'],
  'Offers to you': ['Neked szóló ajánlatok', 'Angebote an dich', 'Offres pour vous', 'Ofertas para ti', 'عروض لك'],
  'Travel routes': ['Útvonalak', 'Reiserouten', 'Itinéraires', 'Rutas', 'طرق السفر'],
  'Trigger an event': ['Esemény indítása', 'Ereignis auslösen', 'Déclencher un événement', 'Provocar un evento', 'إطلاق حدث'],
  'Utility deals': ['Közműszerződések', 'Versorgungsverträge', 'Accords de services publics', 'Acuerdos de suministro', 'صفقات المرافق'],
  // buttons
  'Remove': ['Eltávolítás', 'Entfernen', 'Retirer', 'Quitar', 'إزالة'],
  'Cancel': ['Mégse', 'Abbrechen', 'Annuler', 'Cancelar', 'إلغاء'],
  'Accept': ['Elfogadás', 'Annehmen', 'Accepter', 'Aceptar', 'قبول'],
  'Send': ['Küldés', 'Senden', 'Envoyer', 'Enviar', 'إرسال'],
  'Rename': ['Átnevezés', 'Umbenennen', 'Renommer', 'Renombrar', 'إعادة تسمية'],
  'Repay': ['Visszafizetés', 'Zurückzahlen', 'Rembourser', 'Devolver', 'سداد'],
  'Propose': ['Javaslat', 'Vorschlagen', 'Proposer', 'Proponer', 'اقتراح'],
  'Load': ['Betöltés', 'Laden', 'Charger', 'Cargar', 'تحميل'],
  'Leave': ['Kilépés', 'Verlassen', 'Quitter', 'Salir', 'مغادرة'],
  'Join': ['Csatlakozás', 'Beitreten', 'Rejoindre', 'Unirse', 'انضمام'],
  'Export': ['Exportálás', 'Exportieren', 'Exporter', 'Exportar', 'تصدير'],
  'Erase': ['Törlés', 'Löschen', 'Effacer', 'Borrar', 'مسح'],
  'Overwrite': ['Felülírás', 'Überschreiben', 'Écraser', 'Sobrescribir', 'استبدال'],
  'Save PNG': ['PNG mentése', 'PNG speichern', 'Enregistrer en PNG', 'Guardar PNG', 'حفظ PNG'],
  'Save as new game': ['Mentés új játékként', 'Als neues Spiel speichern', 'Enregistrer comme nouvelle partie', 'Guardar como partida nueva', 'حفظ كلعبة جديدة'],
  'Load game…': ['Játék betöltése…', 'Spiel laden…', 'Charger une partie…', 'Cargar partida…', 'تحميل لعبة…'],
  'Import saved game…': ['Mentett játék importálása…', 'Spielstand importieren…', 'Importer une sauvegarde…', 'Importar partida guardada…', 'استيراد لعبة محفوظة…'],
  'Join multiplayer…': ['Többjátékos csatlakozás…', 'Mehrspieler beitreten…', 'Rejoindre en multijoueur…', 'Unirse al multijugador…', 'الانضمام للعب الجماعي…'],
  'Found a city': ['Város alapítása', 'Stadt gründen', 'Fonder une ville', 'Fundar una ciudad', 'تأسيس مدينة'],
  'Play this city': ['Játék ezzel a várossal', 'Diese Stadt spielen', 'Jouer cette ville', 'Jugar esta ciudad', 'العب هذه المدينة'],
  'Play as governor': ['Játék kormányzóként', 'Als Gouverneur spielen', 'Jouer comme gouverneur', 'Jugar como gobernador', 'العب كحاكم'],
  'Hand to AI': ['Átadás a gépnek', 'An die KI übergeben', "Confier à l'IA", 'Ceder a la IA', 'تسليم للذكاء الاصطناعي'],
  'Host this region': ['A régió megnyitása', 'Diese Region hosten', 'Héberger cette région', 'Alojar esta región', 'استضافة هذا الإقليم'],
  'Open room': ['Szoba nyitása', 'Raum öffnen', 'Ouvrir un salon', 'Abrir sala', 'فتح غرفة'],
  'Follow a resident': ['Egy lakos követése', 'Einem Bewohner folgen', 'Suivre un habitant', 'Seguir a un residente', 'تتبع أحد السكان'],
  'Stop following': ['Követés vége', 'Nicht mehr folgen', 'Arrêter de suivre', 'Dejar de seguir', 'إيقاف التتبع'],
  'Ground view': ['Földi nézet', 'Bodenansicht', 'Vue au sol', 'Vista a pie de calle', 'منظر أرضي'],
  'Return to ground': ['Vissza a felszínre', 'Zurück an die Oberfläche', 'Revenir en surface', 'Volver a la superficie', 'العودة إلى السطح'],
  'Underground bulldozer': ['Földalatti bontás', 'Unterirdischer Abriss', 'Démolition souterraine', 'Demolición subterránea', 'الهدم تحت الأرض'],
  'Export WebM': ['WebM exportálása', 'WebM exportieren', 'Exporter en WebM', 'Exportar WebM', 'تصدير WebM'],
  'Download .organicity file': ['.organicity fájl letöltése', '.organicity-Datei herunterladen', 'Télécharger le fichier .organicity', 'Descargar archivo .organicity', 'تنزيل ملف ‎.organicity'],
  'End contract': ['Szerződés felbontása', 'Vertrag beenden', 'Mettre fin au contrat', 'Terminar contrato', 'إنهاء العقد'],
  'Earthquake': ['Földrengés', 'Erdbeben', 'Séisme', 'Terremoto', 'زلزال'],
  'Tornado': ['Tornádó', 'Tornado', 'Tornade', 'Tornado', 'إعصار'],
  'Festival': ['Fesztivál', 'Festival', 'Festival', 'Festival', 'مهرجان'],
  'Industrial accident': ['Ipari baleset', 'Industrieunfall', 'Accident industriel', 'Accidente industrial', 'حادث صناعي'],
  'Straight': ['Egyenes', 'Gerade', 'Droit', 'Recto', 'مستقيم'],
  'Two-way': ['Kétirányú', 'Zweirichtung', 'Double sens', 'Doble sentido', 'اتجاهين'],
  'Strict grid': ['Szigorú hálózat', 'Strenges Netz', 'Réseau strict', 'Red estricta', 'شبكة صارمة'],
  // labels and states
  'Your name': ['A neved', 'Dein Name', 'Votre nom', 'Tu nombre', 'اسمك'],
  'Server': ['Szerver', 'Server', 'Serveur', 'Servidor', 'الخادم'],
  'Room': ['Szoba', 'Raum', 'Salon', 'Sala', 'الغرفة'],
  'Title': ['Cím', 'Titel', 'Titre', 'Título', 'العنوان'],
  'Map size': ['Térképméret', 'Kartengröße', 'Taille de la carte', 'Tamaño del mapa', 'حجم الخريطة'],
  'Paused': ['Szünet', 'Pausiert', 'En pause', 'En pausa', 'متوقف مؤقتًا'],
  'On': ['Be', 'An', 'Activé', 'Activado', 'تشغيل'],
  'Off': ['Ki', 'Aus', 'Désactivé', 'Desactivado', 'إيقاف'],
  'None': ['Nincs', 'Keine', 'Aucun', 'Ninguno', 'لا شيء'],
  'Residential': ['Lakó', 'Wohnen', 'Résidentiel', 'Residencial', 'سكني'],
  'Commercial': ['Kereskedelmi', 'Gewerbe', 'Commercial', 'Comercial', 'تجاري'],
  'Offices': ['Irodák', 'Büros', 'Bureaux', 'Oficinas', 'مكاتب'],
  'Power': ['Áram', 'Strom', 'Électricité', 'Electricidad', 'الكهرباء'],
  'Water': ['Víz', 'Wasser', 'Eau', 'Agua', 'الماء'],
  'Sewage': ['Szennyvíz', 'Abwasser', 'Eaux usées', 'Aguas residuales', 'الصرف الصحي'],
  'Traffic': ['Forgalom', 'Verkehr', 'Circulation', 'Tráfico', 'حركة المرور'],
  'Pollution': ['Szennyezés', 'Verschmutzung', 'Pollution', 'Contaminación', 'التلوث'],
  'Land value': ['Telekérték', 'Bodenwert', 'Valeur foncière', 'Valor del suelo', 'قيمة الأرض'],
  'Crime': ['Bűnözés', 'Kriminalität', 'Criminalité', 'Delincuencia', 'الجريمة'],
  'Happiness': ['Elégedettség', 'Zufriedenheit', 'Bonheur', 'Felicidad', 'السعادة'],
  // the gallery
  'Gallery': ['Galéria', 'Galerie', 'Galerie', 'Galería', 'المعرض'],
  'Browse gallery': ['Galéria böngészése', 'Galerie ansehen', 'Parcourir la galerie', 'Ver la galería', 'تصفح المعرض'],
  'Submit to gallery': ['Beküldés a galériába', 'In die Galerie einreichen', 'Proposer à la galerie', 'Enviar a la galería', 'إرسال إلى المعرض'],
  'Report': ['Jelentés', 'Melden', 'Signaler', 'Denunciar', 'إبلاغ'],
  'Open': ['Megnyitás', 'Öffnen', 'Ouvrir', 'Abrir', 'فتح'],
  'Close': ['Bezárás', 'Schließen', 'Fermer', 'Cerrar', 'إغلاق'],
};
